# Generated by Django 3.2.7 on 2022-08-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20220830_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Bilgi', 'verbose_name_plural': 'Bilgiler'},
        ),
        migrations.AlterModelOptions(
            name='smmtp',
            options={'verbose_name': 'SMTP', 'verbose_name_plural': 'SMTP Ayarları'},
        ),
        migrations.RenameField(
            model_name='smmtp',
            old_name='smtpsecure',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='smmtp',
            name='host',
        ),
        migrations.AddField(
            model_name='information',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim Url'),
        ),
        migrations.AddField(
            model_name='information',
            name='subtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='information',
            name='informate',
            field=models.CharField(max_length=5000, verbose_name='Bilgi'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='smmtp',
            name='port',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
